services:

  net_tomas_kadlec_d2s.service.application:
    alias: net_tomas_kadlec_d2s.service_application.cached_application

  net_tomas_kadlec_d2s.service_application.application:
    class: Net\TomasKadlec\d2sBundle\Service\Application\Application
    calls:
      - [ setConfiguration, [ "%d2s%" ] ]
      - [ setParser, [ "@net_tomas_kadlec_d2s.service.parser" ] ]
      - [ setOutput, [ "@net_tomas_kadlec_d2s.service.output" ] ]

  net_tomas_kadlec_d2s.service_application.cached_application:
    class: Net\TomasKadlec\d2sBundle\Service\Application\CachedApplication
    parent: net_tomas_kadlec_d2s.service_application.application
    calls:
      - [ setCache, [ "@net_tomas_kadlec_d2s.service.cache" ] ]

  net_tomas_kadlec_d2s.service.parser:
    class: Net\TomasKadlec\d2sBundle\Service\Parser

  net_tomas_kadlec_d2s.service_parser.drest:
    class: Net\TomasKadlec\d2sBundle\Service\Parser\DRest
    tags:
      - { name: net_tomas_kadlec_d2s.service.parser }

  net_tomas_kadlec_d2s.service_parser.utopolu:
    class: Net\TomasKadlec\d2sBundle\Service\Parser\UTopolu
    tags:
      - { name: net_tomas_kadlec_d2s.service.parser }

  net_tomas_kadlec_d2s.service_parser.uprofesora:
    class: Net\TomasKadlec\d2sBundle\Service\Parser\UProfesora
    tags:
      - { name: net_tomas_kadlec_d2s.service.parser }

  net_tomas_kadlec_d2s.service_parser.simigastro:
    class: Net\TomasKadlec\d2sBundle\Service\Parser\SimiGastro
    tags:
      - { name: net_tomas_kadlec_d2s.service.parser }

  net_tomas_kadlec_d2s.service_parser.santinka:
    class: Net\TomasKadlec\d2sBundle\Service\Parser\Santinka
    tags:
      - { name: net_tomas_kadlec_d2s.service.parser }

  net_tomas_kadlec_d2s.service_parser.suz:
    class: Net\TomasKadlec\d2sBundle\Service\Parser\SUZ
    tags:
      - { name: net_tomas_kadlec_d2s.service.parser }

  net_tomas_kadlec_d2s.service.output:
    class: Net\TomasKadlec\d2sBundle\Service\Output

  net_tomas_kadlec_d2s.service_output.slack:
    class: Net\TomasKadlec\d2sBundle\Service\Output\Slack
    tags:
      - { name: net_tomas_kadlec_d2s.service.output }

  net_tomas_kadlec_d2s.service_output.stdout:
    class: Net\TomasKadlec\d2sBundle\Service\Output\StdOut
    tags:
      - { name: net_tomas_kadlec_d2s.service.output }

  net_tomas_kadlec_d2s.service.cache:
    class: Doctrine\Common\Cache\PhpFileCache
    arguments: [ "%kernel.cache_dir%", ".restaurants.php" ]